### ISSUE TITLE
[bug] Dragging element does not work as expected

### ISSUE THREAD

**Issue by spartan-uyen** [onlook-dev/onlook#2061]
**Summary:**
When attempting to resize an element by dragging from its edges, the resize behavior is inverted. For example, dragging from the right affects the left side instead of the right.

**Steps to reproduce:**
1. Select an element on the canvas.
2. Attempt to resize it by dragging from the right or top edge.

**Actual result:**
Dragging from the right edge expands or shrinks the left side.
Dragging from the top edge expands or shrinks the bottom side.
https://github.com/user-attachments/assets/372399b7-923f-4ac8-b4d9-283eb87d6141

**Expected result:**
Dragging from the right should affect the right side.
Dragging from the top should affect the top side.

**Comment by Rish-it** [comment]
@Kitenite I believe the issue has been resolved?

**Comment by Kitenite** [comment]
It's not really resolved but I think it's a minor and somewhat expected behavior

**Comment by Rish-it** [comment]
Hey @Kitenite there was minor mismatch between Coordinate System `handleMouseDownDimensions` causing the issue 

- `calculateNewElementDimensions` was using `adjustedDelta` (canvas-scaled coordinates).
- `calculateNewOverlayDimensions` was using raw `deltaX`, `deltaY` (screen coordinates).

**Comment by Kitenite** [comment]
This seems like it needs more of a UX fix. Perhaps we'd have to hide the left drag accordingly if it's aligned a certain way (similar to Framer). I think this is mostly expected behavior and low priority.
